### ISSUE TITLE
OKR管理项目的方式探讨

### ISSUE THREAD

**Issue by newip** [BUPT/magic-mirror#17]

**Comment by huan** [comment]
A great OKR guide website: [The Ultimate Guide to OKR](https://www.perdoo.com/the-ultimate-okr-guide/)

**Comment by newip** [comment]
### Objectives（20190816-20191031）

1. 在会议室部署硬件并完成测试
1. 自动生成高质量演讲者的 Talk 整合视频
1. 提升 AMC 项目的行业影响力并获取赞助支持
1. 完成系统架构设计（包括硬软件架构）

### Key Results

Key Results 尽量设置的有野心一些。一般来说，竭尽全力的之后能够达到70%指标，是一个合理的设置。

需要注意的是：

```diff
- Key Results 不是我们能够直接能够做的事情的清单
+ Key Results 是能够度量我们达到 Objectives 的指标
+ Key Results 是我们在做完自己该做的事情之后，所希望产生的影响力的结果（并需要量化可测量）
```

#### 1 在会议室部署硬件并完成测试

1. 完成方案所需的所有硬件设备的采购
1. 完成所有硬件的安装、部署、调试
1. 完成硬件的安装、部署、调试文档与资料的整理，为架构设计提供当前部署资料与硬件接口资料
1. 部署完成后完成对硬件维护小组的工作交接
1. 完成资产登记与管理责任人

#### 2 自动生成高质量演讲者的 Talk 整合视频

1. 需要与硬件部署同步进行（克服期间硬件变化的困难），完成对“高质量”的需求整理与设计，提供文档资料，并通过项目组评审
1. 根据设计完成功能的定义、开发、测试、上线，实现整合视频的制作功能
1. 实现视频的线上自动发布功能（官网、YouTube、优酷、B站等）
1. 实现功能模组化，对其他模块的调用提供接口，接口功能需要完成定义、设计、开发、测试、上线

#### 3 提升 AMC 项目的行业影响力并获取赞助支持

1. 每期活动邀请1-2位外部企业或相关组织的人员参加活动
1. 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
1. 实现6家赞助企业、组织、或个人的资金进账，目标资金额30万元或等值设备

#### 4 完成系统架构设计（包括硬软件架构）

1. 初步完成系统框架的设计与原型，完成模块的设置与边界接口定义
1. 对远期硬件架构与硬件需求提出设计与要求
1. 对远期软件架构与部署细节提出设计与要求

**Comment by huan** [comment]
Thanks for creating the first version of our "OKRs" list! :smile: 

The most important when we are using OKRs is that we have to make sure that we are listing the real **Key Results** instead of ~~Initiatives~~ as our Key Results.

According to [What is an OKR?](https://www.perdoo.com/resources/):

> **Key Result**
>
> “How do I know if I’m getting there?” A Key Result shows you how you’re progressing towards your Objective. Think of it as a signpost with a distance marker.
>
> A Key Result is a metric with a starting value and a target value that measures progress towards an Objective.

> **Initiative**
>
> “What will I do to get there?” An Initiative describes what you’ll do to influence your Key Results. Think of it as the description of what you’ll do to get to your destination.
>
> An Initiative is a description of the work you’ll do to influence a Key Result. 

In short, a `Key Result` is "What you can get(outcome)", and the `Initiative` is "What you can do(output)".

| Difference | Outcome V.S. Output | Influence V.S. Control | Value V.S. Activity |
| --- | --- | --- | --- |
| Key Result | What you can GET (outcome) | You cannot control it, you can only INFLUENCE it | Value-based |
| Initiative      | What you can DO (output) | You can CONTROL it directly | Activity-based |

At last, `Key Results` must be **measurable**.

Let's review the following "Results" and to see whether it's a "Key Result(Outcome)" or an "Initiative(Output)"

1. Initiative 完成方案所需的所有硬件设备的采购
2. Key Result(need to be measurable) 完成所有硬件的安装、部署、调试
3. Key Result(need to be measurable) 完成硬件的安装、部署、调试文档与资料的整理，为架构设计提供当前部署资料与硬件接口资料
4. Initiative 部署完成后完成对硬件维护小组的工作交接
5. Initiative 完成资产登记与管理责任人
6. 需要与硬件部署同步进行（克服期间硬件变化的困难），完成对“高质量”的需求整理与设计，提供文档资料，并通过项目组评审
7. Key Result(need to be measurable) 根据设计完成功能的定义、开发、测试、上线，实现整合视频的制作功能
8. Key Result(need to be measurable) 实现视频的线上自动发布功能（官网、YouTube、优酷、B站等）
9. Key Result(need to be measurable) 实现功能模组化，对其他模块的调用提供接口，接口功能需要完成定义、设计、开发、测试、上线
10. Key Result 每期活动邀请1-2位外部企业或相关组织的人员参加活动
11. Key Result 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
12. Key Result 实现6家赞助企业、组织、或个人的资金进账，目标资金额30万元或等值设备
13. Key Result(need to be measurable) 初步完成系统框架的设计与原型，完成模块的设置与边界接口定义
14. Initiative 对远期硬件架构与硬件需求提出设计与要求
15. Initiative 对远期软件架构与部署细节提出设计与要求

It's a good start for us to break down this list and discuss on top of them, make sure we are following the right OKR concepts before we move forward future.

The initiatives are necessary because they will support our Key Results, however, they should be listed separately, and keep them out of our Key Results.

Could you please refine the list above, and make a new version of them so that they will more like Key Results?

**Comment by newip** [comment]
### Objectives（20190816-20191031）

1. 在会议室部署硬件并完成测试
1. 自动生成高质量演讲者的 Talk 整合视频
1. 提升 AMC 项目的行业影响力并获取赞助支持
1. 完成系统架构设计（包括硬软件架构）

### Key Results

Key Results 尽量设置的有野心一些。一般来说，竭尽全力的之后能够达到70%指标，是一个合理的设置。

需要注意的是：

```diff
- Key Results 不是我们能够直接能够做的事情的清单
+ Key Results 是能够度量我们达到 Objectives 的指标
+ Key Results 是我们在做完自己该做的事情之后，所希望产生的影响力的结果（并需要量化可测量）
```

#### 1 在会议室部署硬件并完成测试

1. 完成所有硬件的采购、安装、部署、调试
1.1. 以支持功能设计的硬件齐备、系统架构组认可为准
2. 完成硬件的安装、部署、调试文档与资料的整理，为架构设计提供当前部署资料与硬件接口资料
2.1. 在github上提交正式的文档，并通过项目组评审认可
3. 有明确的责任人对硬件环境进行管理与日常维护
3.1 部署完成后完成对硬件维护小组的工作交接
3.2 完成资产登记与管理责任人

#### 2 自动生成高质量演讲者的 Talk 整合视频

1. 需要与硬件部署同步进行（克服期间硬件变化的困难），完成对“高质量”的需求整理与设计，提供文档资料，并通过项目组评审
1. 根据设计完成功能的定义、开发、测试、上线，实现整合视频的制作功能
2.1. 每一个步骤需要有记录、有评审过程、有评审意见
1. 实现视频的线上自动发布功能（官网、YouTube、优酷、B站等）
1. 实现功能模组化，对其他模块的调用提供接口，接口功能需要完成定义、设计、开发、测试、上线
3.1 以实现一个小Demo，完成对接口的调用示例为准。

#### 3 提升 AMC 项目的行业影响力并获取赞助支持

1. 每期活动邀请1-2位外部企业或相关组织的人员参加活动
1. 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
1. 实现6家赞助企业、组织、或个人的资金进账，目标资金额30万元或等值设备

#### 4 完成系统架构设计（包括硬软件架构）

1. 初步完成系统框架的设计与原型，完成模块的设置与边界接口定义
1. 形成对未来系统架构的设想与规划文档
2.1. 对远期硬件架构与硬件需求提出设计与要求
2.2. 对远期软件架构与部署细节提出设计与要求

**Comment by newip** [comment]
> Almost anything can be measured. If you’re struggling to find Key Results for an Objective, ask yourself “How will I know when my Objective has been achieved?”. Make sure to choose Key Results that are outcome based, look for metrics you don’t directly own or control, but that you can influence.

**Comment by huan** [comment]
I leave my inline-reviews as the following, and please feel free to let me know if I was wrong because I'm also a newbie for learning what is a KR and what is an Initiative.

一 在会议室部署硬件并完成测试

1. 完成所有硬件的采购、安装、部署、调试
    * 以支持功能设计的硬件齐备、系统架构组认可为准

> How can we measure the _系统架构组认可_? Can we specify a measurable metric by a number? 
> If we can not specify a number for this result, could we find a way to make sure the team member will be able to know whether they can get _系统架构组认可_ without asking any people?

1. **not measurable** 完成硬件的安装、部署、调试文档与资料的整理，为架构设计提供当前部署资料与硬件接口资料
    * **this is an initiative** 在github上提交正式的文档，
    * **this is not measurable without asking people** 并通过项目组评审认可
1. **this is an initiative** 有明确的责任人对硬件环境进行管理与日常维护
    * **initiative** 部署完成后完成对硬件维护小组的工作交接
    * **initiative** 完成资产登记与管理责任人

二 自动生成高质量演讲者的 Talk 整合视频

1. **cannot measurable without asking people** 需要与硬件部署同步进行（克服期间硬件变化的困难），完成对“高质量”的需求整理与设计，提供文档资料，并通过项目组评审
1. **Key Result** 根据设计完成功能的定义、开发、测试、上线，实现整合视频的制作功能
    * **initiative** 每一个步骤需要有记录、有评审过程、有评审意见
1. **Key Result, remove "等" will be better, which will make it very clear that this KR is related to 4 sites** 实现视频的线上自动发布功能（官网、YouTube、优酷、B站等）
1. **The requirement is too wide, not specific** 实现功能模组化，对其他模块的调用提供接口，接口功能需要完成定义、设计、开发、测试、上线
    * **Key Result, will be better to define what is the 接口调用示例** 以实现一个小Demo，完成对接口的调用示例为准。

三 提升 AMC 项目的行业影响力并获取赞助支持

1. **Key Result** 每期活动邀请1-2位外部企业或相关组织的人员参加活动
1. **Key Result** 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
1. **Key Result** 实现6家赞助企业、组织、或个人的资金进账，目标资金额30万元或等值设备

四 完成系统架构设计（包括硬软件架构）

1. **Key Result, but need to be measurable** 初步完成系统框架的设计与原型，完成模块的设置与边界接口定义
1. **Initiative** 形成对未来系统架构的设想与规划文档
    * **Initiative** 对远期硬件架构与硬件需求提出设计与要求
    * **Initiative** 对远期软件架构与部署细节提出设计与要求

#### 5 建立会员自主开发小模块的机制与模块池

1. **Initiative** 完成比如计时器之类的小模块1-5个
1. **Initiative** 建立待集成的功能模块池

At last, I believe it will be better if we can keep no more than three objectives for our organization. (currently, we have four in this list)

**Comment by qhduan** [comment]
I have some questions.

- When I google 'initiative', most results lead me to 'The Ultimate Guide to OKR', is this a new concept Perdoo invent it?
- Do we need both of Initiative and Key Result under an Objective?

**Comment by huan** [comment]
@qhduan Short answer to your questions:

1. I get the `initiative` concept from the Perdoo, and it's very likely a concept defined by Perdoo.
1. I believe we do not have to use the Initiatives with KRs together. Because OKRs is all about the KRs, not the initiatives.

Long answer:

When we are planning to do something, we are very likely to define a list of todos, because we can control it very easily, like

> I will write 3 blogs this week.

However, the above description will miss the direction of why we need to do that, and what we want to get an outcome of that action. So we need to move into the high level of a todo description, defines what we want to get as a result of our actions:

> I will get my new blogs read by 1,000 chatbot developers.

The above result will not be able to be controlled by ourselves, but we can only influence it, which means we have to write a better blog so that the readers will share it, and we have to think about how to spread the blog article to cover the target users (chatbot developers in this case).

So, I believe the reason the Padoo introduce the initiative concept to OKRs is that everyone wants to have a TODO list for their OKRs, which could make them more comfortable. And they always want to put a TODO list as the Key Results, which is not right and needs to be clarified.

More information about the KR & Initiative had been discussed in my previous post:

> **Key Result**
>
> “How do I know if I’m getting there?” A Key Result shows you how you’re progressing towards your Objective. Think of it as a signpost with a distance marker.
>
> A Key Result is a metric with a starting value and a target value that measures progress towards an Objective.

> **Initiative**
>
> “What will I do to get there?” An Initiative describes what you’ll do to influence your Key Results. Think of it as the description of what you’ll do to get to your destination.
>
> An Initiative is a description of the work you’ll do to influence a Key Result. 

In short, a `Key Result` is "What you can get(outcome)", and the `Initiative` is "What you can do(output)".

| Difference | Outcome V.S. Output | Influence V.S. Control |
| --- | --- | --- |
| Key Result | What you can GET (outcome) | You cannot control it, you can only INFLUENCE it |
| Initiative      | What you can DO (output) | You can CONTROL it directly |

I hope this post could answer your questions, and please feel free let me know if you have any other questions and let's break down our MM project OKRs together!

**Comment by qhduan** [comment]
initiative is too easier than KR
:sob:

**Comment by newip** [comment]
Let's just focus on the definition of KR “a Key Result is ‘What you can get(outcome)’”. 

一 MM项目所需运行的硬件环境在821会议室完成部署

1. 支持会议数据采集的麦克风“阵列”、扬声器、摄像头“阵列”、运行系统与AI算法所需的工作站、网络环境完成采购、安装、部署、调试。并在硬件不能满足需求时及时补充，最终形成一套可用的硬件、硬件配置、硬件接口与网络环境构成的MM系统硬件环境。
1. 为方便管理与迭代，硬件环境需要在Github上有安装记录、配置信息、部署方式、调试文档、负责人信息。

二 自动生成高质量演讲者的 Talk 整合视频在AMC活动中得以使用

1. 作为MM项目一期交付的功能，需要自动生成带有演讲者跟随视窗、演讲者屏幕显示视窗、AMC Logo的整合视频。 
1. 实现视频的线上自动发布功能（AMC官网、YouTube、优酷、B站）
1. 初步完成具备个性化可配置视窗管理功能的MM项目系统框架的设计与原型，完成模块的设置与边界接口定义
1. 完成比如计时器之类的小模块1-5个，作为待集成的功能模块池

三 提升 AMC 项目的行业影响力并获取赞助支持

1. 每期活动邀请1-2位外部企业或相关组织的人员参加活动
1. 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
1. 实现6家赞助企业、组织、或个人的资金进账，目标资金额20万元或等值设备

Seems better?

**Comment by huan** [comment]
Yes, it looks better than before now, thanks for the update!

The Key Result needs to be an outcome(what we get) instead of output(what we do). At the same time, we have to make sure KRs are value-based, measurable with metrics, and most importantly, should be short.

1. Measurable: Key results are measurable and should be easy to grade with a number (Google uses a scale of 0 – 1.0, I believe we should follow this number range for our AMC projects too)
1. Short: as short as possible
1. Value-based

For an Objective update example, in 1958 NASA had 8 goals including examples like:

> “The establishment of long-range studies of the potential benefits to be gained from, the opportunities for, and the problems involved in the utilization of aeronautical and space activities for peaceful and scientific purposes.”

By 1961, thanks to Kennedy, NASA had one Ultimate goal:

> “Before the decade is out, land a man on the moon and return him safely to earth”.

A short goal will make it easy to be understood, so we should always prevent long descriptions.

So let's continue discussing our previous version of KRs, and to see how to keep improving them:

1. **Need to be value-based, and short** 支持会议数据采集的麦克风“阵列”、扬声器、摄像头“阵列”、运行系统与AI算法所需的工作站、网络环境完成采购、安装、部署、调试。并在硬件不能满足需求时及时补充，最终形成一套可用的硬件、硬件配置、硬件接口与网络环境构成的MM系统硬件环境。
    > 我建议改为：**主指向麦克风**安装 + 供电 + 音频线 + USB声卡 + Linux驱动读取工作流程正常，能够在GPU Station上完成录制音频文件
1. **Need to be measurable by a number from 0 to 1, and value-based** 为方便管理与迭代，硬件环境需要在Github上有安装记录、配置信息、部署方式、调试文档、负责人信息。
    > 我建议改为：每个功能模块都在 Github 有独立的目录和 README ，**AMC会员应能根据 README 在60分钟内完成初次配置**
1. **Need to break down & easy** 作为MM项目一期交付的功能，需要自动生成带有演讲者跟随视窗、演讲者屏幕显示视窗、AMC Logo的整合视频。 
    > 我建议改为至少两个KRs：
    > 每个演讲者演讲完成之后，能够**保存上台开始至下台结束的音视频文件**
    > 能够将演讲者视频+大屏幕视频，**按照模板输出成新MP4文件**
1. **Need to be measurable by a number from 0 to 1** 实现视频的线上自动发布功能（AMC官网、YouTube、优酷、B站）
    > 建议改为：能够将视频通过命令行工具发布到4个视频网站（YouTube、优酷、B站、腾讯）
1. **Need to be measurable by a number from 0 to 1** 初步完成具备个性化可配置视窗管理功能的MM项目系统框架的设计与原型，完成模块的设置与边界接口定义
1. 完成比如计时器之类的小模块1-5个，作为待集成的功能模块池
1. **Needs to be specific: 1 or 2? 企业 or 组织?** 每期活动邀请1-2位外部企业或相关组织的人员参加活动
1. **Needs to be measurable: 1 or 3?** 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
1. 实现6家赞助企业、组织、或个人的资金进账，目标资金额20万元或等值设备

The above comments are my 2 cents, so please feel free to let me know what you thought, and please correct me if I'm wrong. Thanks.

**Comment by VDeamoV** [comment]
Everything seems great. However, in my opinion, the Objective2 (Improve the AMC's influence) can be delay to the next round, for it is hard to do a presentation when we have nothing right, this part may delay util hardware set up finished. Besides, design for the total software framework maybe much more important, for only when the whole project framework are basically fixed, contributors can then dive into more specific part.

So, change Object2(improve the AMC's influence) to System Architecture Design may accelerate the whole progress.

>Object 完成整体系统架构设计

> KR1 明确整体系统需要核心模块的数量和功能、能明确每个模块的功能
> KR2 明确每个模块的接口和输入输出、确保模块组合组合后能正常运作
> KR3 针对模块和系统撰写文档、确保开发者能在60分钟内了解模块的需求

**Comment by huan** [comment]
@VdeamoV thanks for sharing your thoughts!

However, I believe everything are far beyond great, but is a beginning of our very poor version of KRs with lots of mistakes.

About the Objective 2, I believe it's a need for us from thinking from now. However, different team (members) can take different Objectives and KRs , so I think it will not prevent you from focused on the software part of the OKRs.

**Comment by limingth** [comment]
> 3 提升 AMC 项目的行业影响力并获取赞助支持
每期活动邀请1-2位外部企业或相关组织的人员参加活动
每周对接1-3家潜在赞助单位，进行MM项目的deck展示
实现6家赞助企业、组织、或个人的资金进账，目标资金额30万元或等值设备

The most important thing here, I think, is how to value "行业影响力" and how to define "提升". 
Weekly Initiatives should not be taken as KR, there will be no help to clarify our values and metrics.
As a new comer, I still have no idea of what is our outcome about "提升行业影响力".

Good KR can help us to know exactly what level we want to achieve at the end of road.
If we value "行业影响力" as High-level Connectivity, then KR should include "行业排前10的企业都参加过AMC的活动";
If we value "行业影响力" as 
Media Exposure, then KR should include "行业主流媒体至少有3家报道我们AMC的活动";
If we define "提升" as Double Number, then KR should include "外部合作企业数量实现了翻倍增长";
If we define "提升" as Improve Quality, then KR should include "外部合作企业80%都来自于世界500强";

To let everyone in this team have **One Same Standard** of understanding **what we can get** from our objective achievement, then we need think more about KR and what value it represents instead of what activities we will do.

**Comment by newip** [comment]
Hi All，经过一周多的讨论，我们成功的完成的第一阶段三个月的AMC的OKR制定，下一步将是完成各个分组的OKR设定。现将AMC的OKR正式发布于此，同时实时的更新会在OKR [表格的链接](https://docs.google.com/spreadsheets/d/1w_utY3jjBlQI0PCzMM67DewMbp4nSXqVy0bMtP6YyYk/edit?ts=5d569177#gid=0) 


Objective | 完成 821 会议室的硬件部署和测试
-- | --
Key Result | 安装 Camera，并在 linux 下可以读取到 /dev/xxx
Key Result | 安装指向性 mic，在 linux 下录音
Key Result | 完成 GPU Work Station 选型安装至可用状态

Objective | 自动生成高质量演讲者的 Talk 整合视频
-- | --
Key Result | 自动分割演讲者上台下台视频，为后期合成做准备
Key Result | 能够安装制定参数对音频、视频、大屏幕进行裁剪合并，并提供实时接口
Key Result | 能够按照模版对音频、视频、大屏幕进行拼接输出最终文件

Objective | 吸引充足的行业伙伴对 AMC 进行项目支持
-- | --
Key Result | 完成三次大型活动 AMC 演讲
Key Result | 发布项目介绍文案达到 1000 个潜在受众（开发人员，从业人员以及潜在的赞助者）
Key Result | 获取20万RMB的行业赞助费用

同时，我们也为这三个Objective确认了工作小组以及负责人：
* 硬件组，组长 @ArronHZG 
* 系统组，组长 @VDeamoV 
* 外联组，组长 @secortot

分组OKR设定本周内由各位组长完成，并更新到OKR文件中。
会议时间为9月1日下午1点钟（本周日）。请各位组长 @ArronHZG @VDeamoV @secortot在周六中午前完成文件的更新，并在微信上通知小组，以便参加会议的人员可以提前了解需要讨论的内容。

另外，各位组长也可以开始团队成员的邀请，以便开展工作的执行。

**Comment by VDeamoV** [comment]
这边来总结下之前在开会时候的一些经验性的总结，目前软件组的工作方面可能没有

## 个人的参会总结
- 第一个是周日进行的讨论其实可以理解为一个 Sprint，人数大约在 5-7 人
- 最后小组 leader 总结上面，最后一步其实就不是讨论了，应该直接下结论，阐述的内容应该是我为什么觉得，而不应该在我要如何劝说别人支持我。
- 在听的时候把想说的先写下来，除非特别重要的不要直接打断，这样会拖慢会议进度
- 不要便利贴贴在白板上再写
- 中文表达有时候准确性不好，如果能用英文精准表达的话就用中英混合的方式表达就好
- 定计划的时候要有野心，要定在小组能力边界，甚至超出一部分的目标
- 制定计划的时候，**要先调研我们有什么**，比如定计划的时候需要先了解当前团队的人员的能力，已有的资源有哪些。

**Comment by huan** [comment]
@VDeamoV It's great to read your notes after the meeting!

I'm looking forward to reading the notes from other team leaders! @ArronHZG @secortot

**Comment by huan** [comment]
The discussion from this issue had been moved to Google Docs.

### AMC OKR Meeting Notes

<https://docs.google.com/document/d/1OWBVUvM3lQrwOURdhEGgvR4xaVCc5ZG1F4D7MR3jKFQ>

**Comment by newip** [comment]
> Let's just focus on the definition of KR “a Key Result is ‘What you can get(outcome)’”.
> 
> 一 MM项目所需运行的硬件环境在821会议室完成部署
> 
> 1. 支持会议数据采集的麦克风“阵列”、扬声器、摄像头“阵列”、运行系统与AI算法所需的工作站、网络环境完成采购、安装、部署、调试。并在硬件不能满足需求时及时补充，最终形成一套可用的硬件、硬件配置、硬件接口与网络环境构成的MM系统硬件环境。
> 2. 为方便管理与迭代，硬件环境需要在Github上有安装记录、配置信息、部署方式、调试文档、负责人信息。
> 
> 二 自动生成高质量演讲者的 Talk 整合视频在AMC活动中得以使用
> 
> 1. 作为MM项目一期交付的功能，需要自动生成带有演讲者跟随视窗、演讲者屏幕显示视窗、AMC Logo的整合视频。
> 2. 实现视频的线上自动发布功能（AMC官网、YouTube、优酷、B站）
> 3. 初步完成具备个性化可配置视窗管理功能的MM项目系统框架的设计与原型，完成模块的设置与边界接口定义
> 4. 完成比如计时器之类的小模块1-5个，作为待集成的功能模块池
> 
> 三 提升 AMC 项目的行业影响力并获取赞助支持
> 
> 1. 每期活动邀请1-2位外部企业或相关组织的人员参加活动
> 2. 每周对接1-3家潜在赞助单位，进行MM项目的deck展示
> 3. 实现6家赞助企业、组织、或个人的资金进账，目标资金额20万元或等值设备
> 
> Seems better?

test
